# Import Libraries

In [6]:
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
womens_world_cup_stats = pd.read_csv(
    '/Users/gui/womens_world_cup_2023_statsbomb_finalfinal.csv'
)

# Official Rankings & Performance

In [9]:
official_rankings = {
    "A": ["Switzerland", "Norway", "New Zealand", "Philippines"],
    "B": ["Australia", "Nigeria", "Canada", "Ireland"],
    "C": ["Japan", "Spain", "Zambia", "Costa Rica"],
    "D": ["England", "Denmark", "China", "Haiti"],
    "E": ["Netherlands", "USA", "Portugal", "Vietnam"],
    "F": ["France", "Jamaica", "Brazil", "Panama"],
    "G": ["Sweden", "South Africa", "Italy", "Argentina"],
    "H": ["Colombia", "Morocco", "Germany", "South Korea"]
}

performance_rankings = {
    "A": ["Norway", "Switzerland", "New Zealand", "Philippines"],
    "B": ["Australia", "Nigeria", "Canada", "Ireland"],
    "C": ["Japan", "Spain", "Zambia", "Costa Rica"],
    "D": ["England", "Denmark", "Haiti", "China"],
    "E": ["Netherlands", "USA", "Portugal", "Vietnam"],
    "F": ["France", "Brazil", "Jamaica", "Panama"],
    "G": ["Sweden", "South Africa", "Italy", "Argentina"],
    "H": ["Colombia", "Germany", "Morocco", "South Korea"]
}

# Final Dataset

In [11]:
rows = []

for group in official_rankings:
    for rank in range(4):
        team = official_rankings[group][rank]
        performance_rank = performance_rankings[group].index(team) + 1
        
        rows.append({
            "Group": group,
            "Team": team,
            "Official_Rank": rank + 1,
            "Performance_Rank": performance_rank
        })

group_rankings = pd.DataFrame(rows)

group_rankings

   Group          Team  Official_Rank  Performance_Rank
0      A   Switzerland              1                 2
1      A        Norway              2                 1
2      A   New Zealand              3                 3
3      A   Philippines              4                 4
4      B     Australia              1                 1
5      B       Nigeria              2                 2
6      B        Canada              3                 3
7      B       Ireland              4                 4
8      C         Japan              1                 1
9      C         Spain              2                 2
10     C        Zambia              3                 3
11     C    Costa Rica              4                 4
12     D       England              1                 1
13     D       Denmark              2                 2
14     D         China              3                 4
15     D         Haiti              4                 3
16     E   Netherlands              1                 1
17     E           USA              2                 2
18     E      Portugal              3                 3
19     E       Vietnam              4                 4
20     F        France              1                 1
21     F       Jamaica              2                 3
22     F        Brazil              3                 2
23     F        Panama              4                 4
24     G        Sweden              1                 1
25     G  South Africa              2                 2
26     G         Italy              3                 3
27     G     Argentina              4                 4
28     H      Colombia              1                 1
29     H       Morocco              2                 3
30     H       Germany              3                 2
31     H   South Korea              4                 4

## Diference between rankings

In [13]:
group_rankings["Rank_Difference"] = (
    group_rankings["Official_Rank"] -
    group_rankings["Performance_Rank"]
)

group_rankings

   Group          Team  Official_Rank  Performance_Rank  Rank_Difference
0      A   Switzerland              1                 2               -1
1      A        Norway              2                 1                1
2      A   New Zealand              3                 3                0
3      A   Philippines              4                 4                0
4      B     Australia              1                 1                0
5      B       Nigeria              2                 2                0
6      B        Canada              3                 3                0
7      B       Ireland              4                 4                0
8      C         Japan              1                 1                0
9      C         Spain              2                 2                0
10     C        Zambia              3                 3                0
11     C    Costa Rica              4                 4                0
12     D       England              1                 1                0
13     D       Denmark              2                 2                0
14     D         China              3                 4               -1
15     D         Haiti              4                 3                1
16     E   Netherlands              1                 1                0
17     E           USA              2                 2                0
18     E      Portugal              3                 3                0
19     E       Vietnam              4                 4                0
20     F        France              1                 1                0
21     F       Jamaica              2                 3               -1
22     F        Brazil              3                 2                1
23     F        Panama              4                 4                0
24     G        Sweden              1                 1                0
25     G  South Africa              2                 2                0
26     G         Italy              3                 3                0
27     G     Argentina              4                 4                0
28     H      Colombia              1                 1                0
29     H       Morocco              2                 3               -1
30     H       Germany              3                 2                1
31     H   South Korea              4                 4                0

In [14]:
group_rankings["Movement"] = group_rankings["Rank_Difference"].apply(
    lambda x: "Up" if x > 0 else "Down" if x < 0 else "Same"
)

group_rankings

,Group,Team,Official_Rank,Performance_Rank,Rank_Difference,Movement
0,A,Switzerland,1,2,-1,Down
1,A,Norway,2,1,1,Up
2,A,New Zealand,3,3,0,Same
3,A,Philippines,4,4,0,Same
4,B,Australia,1,1,0,Same
5,B,Nigeria,2,2,0,Same
6,B,Canada,3,3,0,Same
7,B,Ireland,4,4,0,Same
8,C,Japan,1,1,0,Same
9,C,Spain,2,2,0,Same
10,C,Zambia,3,3,0,Same
11,C,Costa Rica,4,4,0,Same
12,D,England,1,1,0,Same
13,D,Denmark,2,2,0,Same
14,D,China,3,4,-1,Down
15,D,Haiti,4,3,1,Up
16,E,Netherlands,1,1,0,Same
17,E,USA,2,2,0,Same
18,E,Portugal,3,3,0,Same
19,E,Vietnam,4,4,0,Same
20,F,France,1,1,0,Same
21,F,Jamaica,2,3,-1,Down
22,F,Brazil,3,2,1,Up
23,F,Panama,4,4,0,Same
24,G,Sweden,1,1,0,Same
25,G,South Africa,2,2,0,Same
26,G,Italy,3,3,0,Same
27,G,Argentina,4,4,0,Same
28,H,Colombia,1,1,0,Same
29,H,Morocco,2,3,-1,Down
30,H,Germany,3,2,1,Up
31,H,South Korea,4,4,0,Same

In [15]:
group_stage = womens_world_cup_stats[
    womens_world_cup_stats["stage"] == "Group"
].copy()

group_stage.shape

(96, 53)

In [26]:
group_stage = pd.concat(
    [group_stage],
    ignore_index=True
).copy()

In [28]:
def min_max_score(series):
    if series.max() == series.min():
        return 50
    return ((series - series.min()) / (series.max() - series.min())) * 100

# CREATE THE SCORE OF THE 5 METRICS

In [33]:
group_stage["xG_score"] = min_max_score(
    group_stage["xG"]
)

group_stage["pass_accuracy_score"] = min_max_score(
    group_stage["pass_accuracy_pct"]
)

group_stage["possession_score"] = min_max_score(
    group_stage["possession_pct"]
)

group_stage["goals_scored_score"] = min_max_score(
    group_stage["goals_for"]
)

group_stage["goals_conceded_score"] = (
    100 - min_max_score(group_stage["goals_against"])
)

# PERFORMANCE SCORE

In [36]:
group_stage["performance_score"] = (
    group_stage["xG_score"] * 0.25 +
    group_stage["pass_accuracy_score"] * 0.25 +
    group_stage["possession_score"] * 0.10 +
    group_stage["goals_scored_score"] * 0.25 +
    group_stage["goals_conceded_score"] * 0.15
)

In [38]:
group_stage["performance_score"] = group_stage["performance_score"].round(1)

# FINAL TABLE

In [41]:
performance_table = group_stage[
    [
        "team",
        "xG",
        "pass_accuracy_pct",
        "possession_pct",
        "goals_for",
        "goals_against",
        "performance_score"
    ]
].copy()

performance_table = performance_table.sort_values(
    "performance_score",
    ascending=False
).reset_index(drop=True)



performance_table.insert(
    0,
    "Rank",
    range(1, len(performance_table) + 1)
)


performance_table["xG"] = (
    performance_table["xG"].round(1)
)

performance_table["pass_accuracy_pct"] = (
    performance_table["pass_accuracy_pct"].round(1)
)

performance_table["possession_pct"] = (
    performance_table["possession_pct"].round(1)
)


performance_table = performance_table.rename(columns={
    "team": "Team",
    "xG": "xG (%)",
    "pass_accuracy_pct": "Pass Accuracy (%)",
    "possession_pct": "Possession (%)",
    "goals_for": "Goals Scored",
    "goals_against": "Goals Conceded",
    "performance_score": "Performance Score"
})



performance_table

,Rank,Team,xG (%),Pass Accuracy (%),Possession (%),Goals Scored,Goals Conceded,Performance Score
0,1,Netherlands Women's,4.2,87.1,73.2,7,0,95.7
1,2,Norway Women's,3.5,83.2,69.6,6,0,85.0
2,3,Japan Women's,4.6,79.4,67.9,5,0,85.0
3,4,Spain Women's,3.8,85.6,68.8,5,0,84.4
4,5,Spain Women's,4.2,84.1,83.8,3,0,80.7
...,...,...,...,...,...,...,...,...
91,92,Morocco Women's,0.2,62.8,29.7,0,6,14.3
92,93,Vietnam Women's,0.0,52.7,28.6,0,3,13.3
93,94,Vietnam Women's,0.3,62.9,26.8,0,7,12.3
94,95,Philippines Women's,0.1,56.8,30.4,0,6,10.4
95,96,Costa Rica Women's,0.1,48.0,16.2,0,3,9.3

In [48]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

performance_table

,Rank,Team,xG (%),Pass Accuracy (%),Possession (%),Goals Scored,Goals Conceded,Performance Score
0,1,Netherlands Women's,4.2,87.1,73.2,7,0,95.7
1,2,Norway Women's,3.5,83.2,69.6,6,0,85.0
2,3,Japan Women's,4.6,79.4,67.9,5,0,85.0
3,4,Spain Women's,3.8,85.6,68.8,5,0,84.4
4,5,Spain Women's,4.2,84.1,83.8,3,0,80.7
5,6,Germany Women's,2.3,85.1,70.3,6,0,80.0
6,7,Brazil Women's,3.6,84.0,73.6,4,0,79.4
7,8,England Women's,2.3,87.5,71.1,6,1,79.2
8,9,France Women's,3.3,80.3,63.3,6,3,75.1
9,10,Sweden Women's,3.6,74.7,47.5,5,0,73.5
10,11,Portugal Women's,3.8,82.6,72.7,2,0,72.7
11,12,Switzerland Women's,3.4,87.5,69.8,2,0,72.7
12,13,United States Women's,4.0,74.8,71.4,3,0,71.9
13,14,Japan Women's,2.5,80.6,63.0,2,0,62.6
14,15,England Women's,2.5,85.0,65.9,1,0,62.5
15,16,Australia Women's,3.1,62.2,40.9,4,0,58.5
16,17,Italy Women's,3.2,76.6,63.7,2,3,57.8
17,18,Sweden Women's,1.6,77.8,68.0,2,1,54.9
18,19,Sweden Women's,1.6,77.2,55.9,2,0,54.6
19,20,Denmark Women's,1.8,73.8,56.2,2,0,53.9
20,21,Canada Women's,1.8,77.2,57.8,2,1,53.9
21,22,England Women's,1.0,83.7,65.2,1,0,53.5
22,23,Australia Women's,1.4,80.9,58.0,1,0,53.0
23,24,Australia Women's,2.3,75.5,66.0,2,3,52.8
24,25,Colombia Women's,1.5,71.7,59.1,2,0,51.4
25,26,France Women's,1.9,76.7,69.8,0,0,51.0
26,27,Canada Women's,1.6,79.1,65.7,0,0,50.4
27,28,Germany Women's,1.3,80.6,60.4,1,1,50.3
28,29,China PR Women's,1.3,77.9,46.8,1,0,48.5
29,30,Netherlands Women's,1.2,75.9,55.2,1,0,48.3
30,31,Germany Women's,1.5,79.3,57.9,1,2,48.0
31,32,Brazil Women's,1.3,76.6,70.5,0,0,47.8
32,33,Norway Women's,1.2,78.7,56.7,0,0,46.6
33,34,Costa Rica Women's,2.3,74.0,55.2,1,3,46.5
34,35,Zambia W,1.9,60.9,44.8,3,1,46.4
35,36,Denmark Women's,0.9,74.6,59.9,1,0,46.2
36,37,Nigeria Women's,1.1,81.0,47.5,0,0,46.2
37,38,Japan Women's,0.9,63.1,31.3,4,0,45.7
38,39,New Zealand Women's,1.6,66.2,57.8,1,0,44.8
39,40,Argentina Women's,0.6,75.6,59.9,2,2,44.6
40,41,Korea Republic Women's,1.4,75.3,65.3,0,1,44.6
41,42,Italy Women's,0.5,75.6,56.0,1,0,44.5
42,43,Republic of Ireland Women's,0.5,82.4,52.5,0,0,44.4
43,44,Jamaica Women's,1.0,71.4,51.9,1,0,44.1
44,45,France Women's,0.9,69.1,52.9,2,1,43.5
45,46,Switzerland Women's,0.9,79.2,43.3,0,0,43.5
46,47,South Africa Women's,2.2,63.8,40.1,2,2,43.0
47,48,Netherlands Women's,0.5,78.9,47.8,1,1,42.9
48,49,New Zealand Women's,1.4,71.4,70.5,0,1,42.8
49,50,Spain Women's,0.6,88.3,68.7,0,4,42.3
50,51,Colombia Women's,0.6,78.3,58.7,0,1,41.0
51,52,New Zealand Women's,0.7,73.2,55.0,0,0,40.2
52,53,United States Women's,1.6,65.5,53.6,0,0,40.0
53,54,Morocco Women's,1.7,61.4,41.3,1,0,39.8
54,55,United States Women's,1.0,68.0,52.2,1,1,39.7
55,56,Nigeria Women's,1.2,61.3,34.0,3,2,38.7
56,57,Morocco Women's,1.0,64.6,34.7,1,0,37.2
57,58,Brazil Women's,1.0,68.9,47.1,1,2,37.0
58,59,Switzerland Women's,0.1,75.2,45.0,0,0,36.6
59,60,Haiti Women's,0.8,69.5,53.2,0,1,35.8
60,61,South Africa Women's,0.8,57.9,36.3,3,2,34.8
61,62,Portugal Women's,0.3,69.8,46.4,0,0,34.7
62,63,Colombia Women's,0.5,61.1,42.1,2,1,34.6
63,64,Panama Women's,0.5,70.2,48.1,0,1,34.2
64,65,Argentina Women's,0.2,72.4,44.0,0,1,33.4
65,66,Italy Women's,0.7,78.9,52.5,0,5,32.5
66,67,Costa Rica Women's,0.1,76.8,37.0,0,2,32.4
67,68,Norway Women's,1.0,64.7,42.2,0,1,32.4
68,69,Republic of Ireland Women's,1.0,61.9,42.2,1,2,32.3
69,70,Canada Women's,0.5,74.4,59.1,0,4,32.0
70,71,China PR Women's,0.3,70.7,40.1,0,1,31.9
71,72,Argentina Women's,0.3,70.5,44.1,0,2,30.6
72,73,Korea Republic Women's,1.0,55.6,39.6,1,1,30.1
73,74,Republic of Ireland Women's,0.7,62.2,42.0,0,1,29.3
74,75,Portugal Women's,0.1,66.9,44.8,0,1,29.3
75,76,South Africa Women's,1.0,57.9,32.0,1,2,28.4
76,77,Panama Women's,1.4,53.5,36.7,3,6,27.0
77,78,Denmark Women's,0.5,61.8,34.8,0,1,27.0
78,79,Nigeria Women's,0.5,57.3,34.3,0,0,26.0
79,80,Haiti Women's,0.6,57.3,34.1,0,1,24.8
80,81,Philippines Women's,0.2,65.5,30.2,0,2,24.6
81,82,China PR Women's,1.0,65.1,28.9,1,6,23.7
82,83,Korea Republic Women's,0.3,60.2,40.9,0,2,23.7
83,84,Haiti Women's,0.5,57.6,43.8,0,2,23.6
84,85,Philippines Women's,0.3,47.9,29.5,1,0,22.2
85,86,Vietnam Women's,0.2,58.5,27.3,0,2,19.8
86,87,Jamaica Women's,0.2,51.1,29.5,0,0,19.8
87,88,Jamaica Women's,0.2,50.9,30.2,0,0,19.8
88,89,Zambia W,0.0,68.6,32.1,0,5,19.4
89,90,Panama Women's,0.2,58.6,26.4,0,4,15.4
90,91,Zambia W,0.4,58.4,31.2,0,5,15.2
91,92,Morocco Women's,0.2,62.8,29.7,0,6,14.3
92,93,Vietnam Women's,0.0,52.7,28.6,0,3,13.3
93,94,Vietnam Women's,0.3,62.9,26.8,0,7,12.3
94,95,Philippines Women's,0.1,56.8,30.4,0,6,10.4
95,96,Costa Rica Women's,0.1,48.0,16.2,0,3,9.3

In [45]:
# ==========================================
# SCORE BREAKDOWN
# ==========================================

score_breakdown = group_stage[
    [
        "team",
        "xG_score",
        "pass_accuracy_score",
        "possession_score",
        "goals_scored_score",
        "goals_conceded_score",
        "performance_score"
    ]
].copy()



score_breakdown = score_breakdown.sort_values(
    "performance_score",
    ascending=False
).reset_index(drop=True)



score_breakdown.insert(
    0,
    "Rank",
    range(1, len(score_breakdown) + 1)
)



score_columns = [
    "xG_score",
    "pass_accuracy_score",
    "possession_score",
    "goals_scored_score",
    "goals_conceded_score",
    "performance_score"
]

score_breakdown[score_columns] = (
    score_breakdown[score_columns].round(1)
)



score_breakdown = score_breakdown.rename(columns={
    "team": "Team",
    "xG": "xG (25%)",
    "pass_accuracy_score": "Pass Accuracy Score (25%)",
    "possession_score": "Possession Score (10%)",
    "goals_scored_score": "Goals Scored Score (25%)",
    "goals_conceded_score": "Goals Conceded Score (15%)",
    "performance_score": "Performance Score"
})



score_breakdown

,Rank,Team,xG_score,Pass Accuracy Score (25%),Possession Score (10%),Goals Scored Score (25%),Goals Conceded Score (15%),Performance Score
0,1,Netherlands Women's,91.8,97.2,84.3,100.0,100.0,95.7
1,2,Norway Women's,75.4,87.4,79.0,85.7,100.0,85.0
2,3,Japan Women's,100.0,77.9,76.4,71.4,100.0,85.0
3,4,Spain Women's,81.7,93.3,77.9,71.4,100.0,84.4
4,5,Spain Women's,90.3,89.5,100.0,42.9,100.0,80.7
...,...,...,...,...,...,...,...,...
91,92,Morocco Women's,3.8,36.8,19.9,0.0,14.3,14.3
92,93,Vietnam Women's,0.0,11.7,18.3,0.0,57.1,13.3
93,94,Vietnam Women's,6.0,37.1,15.7,0.0,0.0,12.3
94,95,Philippines Women's,2.4,22.1,21.0,0.0,14.3,10.4
95,96,Costa Rica Women's,2.8,0.2,0.0,0.0,57.1,9.3